texture.composite.colortex4=dither3d_atlas.png
texture.composite.colortex5=dither3d_ramp.png

# Main settings screen
screen=[DITHER_STYLE] [DITHER_PARAMS] [DITHER_ADVANCED]

# Sub-pages
screen.DITHER_STYLE=DITHER_COLOR_MODE INVERSE_DOTS
screen.DITHER_PARAMS=dither_Scale dither_Contrast dither_SizeVariability dither_InputExposure dither_InputOffset
screen.DITHER_ADVANCED=dither_StretchSmoothness RADIAL_COMPENSATION FLIP_ATLAS_LAYERS
